version: '3.9'

services:

  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    command: sh -c "alembic upgrade head &&
        uvicorn server.main:app --reload --host 0.0.0.0 --port 8080"
  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DATABASE} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5



volumes:
  postgres-data: